### ISSUE TITLE
iframe issue

### ISSUE THREAD

**Issue by andrejLido** [scribble-rs/scribble.rs#247] opened 2021-03-10 13:45 UTC
Hi guys,

I tried to run the app in an iframe, and it didn't work for me,
the socket connection is failed.

`ssrEnterLobby:406 WebSocket connection to 'wss://...' failed: HTTP Authentication failed; no valid credentials available`

is there a way to fix it ?

thanks in advance

**Comment by Bios-Marcel** [comment] 2021-03-10 16:43
Please always send your code, used browser, system and environment information, so I can make sure I can reproduce cases as good as possible.

While it doesn't work for me either, I get a totally different error, so even If I fix my problem, I am unsure whether the solution fixes yours.

**Comment by andrejLido** [comment] 2021-03-10 17:14
Hi,

I'm using chrome version 88.0.4324.192 on macbook.
iframe on my my site:
`<iframe height =" 100% "width =" 100% "src =" https://scribblers-official.herokuapp.com "> </iframe>`

When I call the page in firefox, I also get another error:
`[HTTP / 1.1 401 Unauthorized]`

It looks to me as if the session cookie is not set in iframe.
Anyway, I can't find it in the request header:

The issue appears after click on create lobby button

chrome

url:
wss: //scribblers-official.herokuapp.com/v1/ws? lobby_id = d58ac10d-5425-4774-94a0-96324348d859

request header:

`Provisional headers are shown
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6
Cache-Control: no-cache
Connection: Upgrade
Host: scribblers-official.herokuapp.com
Origin: https://scribblers-official.herokuapp.com
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: d5ulJkdJLPQcW3UA1tF/JQ==
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36`

may be something with cross domain stuff...

**Comment by Bios-Marcel** [comment] 2021-03-10 17:21
Totally different topic, why do you want to use an iframe? ^^

**Comment by andrejLido** [comment] 2021-03-10 17:30
I have some web app which is written with completly different stack php/nginx/vue.
And I wanted separate the scribble-game in the another docker container under another subdomain. (separation of concern)
to include scribble in the web-app, I wanted use an iframe.

**Comment by andrejLido** [comment] 2021-03-10 17:32
But maybe you can advice me, how I can allow the cookies for specific domains.
I have an docker Installation and can adjust it maybe on my own...

**Comment by Bios-Marcel** [comment] 2021-03-10 17:37
Uhm, so you want to different docker containers, that run on the same domain, but different subdomain?

Would `page.com/` have `page.com/scribblers` which shows an `iframe` that points to `scribblers.page.com/` which serves scribble.rs?

If that's your plan, I'd suggest to simply host scribblers under `page.com/scribblers`, this is possible by using a reverse proxy and having your docker containers run on for example `8080` and `8181`. Your reverse proxy would then expose 80 (443 with ssl) and redirect `page.com/scribblers/*` to `8181` and `page.com/` to `8080`.

I think you can use nginx for this.

Scribble.rs also allows passing a custom path by setting the environment variable `ROOT_PATH`.

**Comment by andrejLido** [comment] 2021-03-10 17:46
The idea was:
**app container**: mydomain.com
**scribble-container**: scribble.mydomain.com

**index.html in app-container (mydomain.com)**:

`<html>
<body>
<iframe height = "100%" width = "100%" src = "https://scribble.mydomain.com"> </iframe>
</body>
</html>
`

**Comment by Bios-Marcel** [comment] 2021-03-10 17:51
Well I don't think that's possible unless i set the cookie `SameSite` policy to `none; secure`, which would also not allow usage with http (non secure) anymore. The scribble server doesn't even support https right now, it is intended to be used behind a reverse proxy or without https. However, I wouldn't like third party sites being able to grab the cookies I think.

So I understand it that, by default your domain serves nothing at `/` (index) and you wanted to use that for scribble.rs via an iframe?

**Comment by andrejLido** [comment] 2021-03-10 17:53
<img width="1481" alt="Bildschirmfoto 2021-03-10 um 18 50 23" src="https://user-images.githubusercontent.com/8950589/110673979-b6cd7c00-81d1-11eb-9084-f4e7e569a6ad.png">

should looks like this at the end

**Comment by andrejLido** [comment] 2021-03-10 17:58
no, the main domain serves the app, and would include the scribble as an iframe in the layer.
something like this:
<img width="1461" alt="Bildschirmfoto 2021-03-10 um 18 54 25" src="https://user-images.githubusercontent.com/8950589/110674826-92be6a80-81d2-11eb-911c-532bf2d2224f.png">

**Comment by Bios-Marcel** [comment] 2021-03-10 18:04
Oh I see. I thought `/` was empty. Hmmm. I don't see a quick and easy solution for this without changes to the code in this case.

Either way, have you tried it only with the official instance? Because if I do this locally and I host two servers, one at 8080 and one at 8181, it works. Try setting up your second container and try it with that.

**Comment by andrejLido** [comment] 2021-03-10 18:08
ok, Thank you!
will try!

**Comment by Bios-Marcel** [comment] 2021-03-12 17:18
Feel free to close the issue if the problem is solved for you.

**Closed** 2021-03-12 17:25 UTC
Labels: question
