### ISSUE TITLE
Fill tool

### ISSUE THREAD

**Issue by Y-Less** [scribble-rs/scribble.rs#24] opened 2019-07-04 15:37 UTC
Tool to fill with (i.e. flood areas with colour).

**Comment by Bios-Marcel** [comment] 2019-07-04 15:56
Duplicate of #8

**Comment by MarvinKlar** [comment] 2019-07-10 13:51
This feature must be implemented at this location:
https://github.com/scribble-rs/scribble.rs/blob/master/lobby.html#L387

When the player clicks in the drawing area AND has selected the fill tool, the area, zoned by the lines drawed by the player, or the borders of the drawing area, will be filled with the selected color like so:
```
var pixelStack = [[e.offsetX, e.offsetY]];

while(pixelStack.length)
{
  var newPos, x, y, pixelPos, reachLeft, reachRight;
  newPos = pixelStack.pop();
  x = newPos[0];
  y = newPos[1];
  
  pixelPos = (y*canvasWidth + x) * 4;
  while(y-- >= drawingBoundTop && matchStartColor(pixelPos))
  {
    pixelPos -= canvasWidth * 4;
  }
  pixelPos += canvasWidth * 4;
  ++y;
  reachLeft = false;
  reachRight = false;
  while(y++ < canvasHeight-1 && matchStartColor(pixelPos))
  {
    colorPixel(pixelPos);

    if(x > 0)
    {
      if(matchStartColor(pixelPos - 4))
      {
        if(!reachLeft){
          pixelStack.push([x - 1, y]);
          reachLeft = true;
        }
      }
      else if(reachLeft)
      {
        reachLeft = false;
      }
    }
	
    if(x < canvasWidth-1)
    {
      if(matchStartColor(pixelPos + 4))
      {
        if(!reachRight)
        {
          pixelStack.push([x + 1, y]);
          reachRight = true;
        }
      }
      else if(reachRight)
      {
        reachRight = false;
      }
    }
			
    pixelPos += canvasWidth * 4;
  }
}
context.putImageData(colorLayer, 0, 0);
  
function matchStartColor(pixelPos)
{
  var r = colorLayer.data[pixelPos];	
  var g = colorLayer.data[pixelPos+1];	
  var b = colorLayer.data[pixelPos+2];

  return (r == startR && g == startG && b == startB);
}

function colorPixel(pixelPos)
{
  var d = document.createElement("div");
  d.style.color = localColor;
  var colorProperty = window.getComputedStyle(d, null).getPropertyValue("color");
  var rgb = colorProperty.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/);

  colorLayer.data[pixelPos] = rgb[1];
  colorLayer.data[pixelPos+1] = rgb[2];
  colorLayer.data[pixelPos+2] = rgb[3];
  colorLayer.data[pixelPos+3] = 255;
}
```

**Comment by bttrs** [comment] 2020-03-19 19:53
So, implementing a flood fill isn't the difficult part of this issue. 
The problem is, it currently results into ugly patterns at the edge of the filled area:
![2020-03-19 20_22_07-Scribble rs - Game](https://user-images.githubusercontent.com/7150765/77106424-57ee8000-6a1f-11ea-8213-63e3124f414f.png)
This is because the canvas line drawing methods
`context.moveTo(x1, y1);
 context.lineTo(x2, y2);
 context.stroke();` WILL add anti-aliasing. As far as my googling skills took my, this is unfortunately unavoidable.

Thoughts on solutions:
1. Change the way lines are drawn onto the canvas. This could be done completely 'manual' with changing each pixel manually via `ImageData`.
i don't really know how to do this with lines bigger than one pixel. For example there is this algorith called [bresenham's algorithm](http://members.chello.at/~easyfilter/bresenham.html), but with the direction semi-randomly (following the mouse) changing, this also would result in a really funny and ugly line.

2. Anti-aliasing can be turned of when drawin images onto the canvas, maybe that path is worth investigating.

3. Since we have a fix set of colors, we can change the way we check pixels for the flood filling. Usually, a check would be very simple. If we click on a pixel, we save its original color in a variable, and change its color. If the neighboring pixels would have the same original color, we would change them.
We could expand it by also checking if the corresponding pixels are anti-aliased (-> not in the color list). This might take a toll on performance, but i am not sure how much.


What do you think?

**Comment by Bios-Marcel** [comment] 2020-03-19 20:38
Yeah, i came to the exact ssme conclusions already. The only solution seems to be a self-implemented drawing algorithm that directly manipulates the buffer. And the color set technically isn't limited. (Click the rectangle on the left)

**Comment by bttrs** [comment] 2020-03-19 22:36
ah snap. yes then the custom buffer manipulation it is.

**Comment by Bios-Marcel** [comment] 2020-03-23 21:53
Done with 02103d606862b97cd68917daffd298d4bc466d9d and 6787e2c09da295c2e3d0f117a4bd01c2a336ec34

**Closed by Bios-Marcel** 2020-03-23 21:53 UTC
Labels: feature-request, good first issue, help wanted
