### ISSUE TITLE
Pencil sizes are sometimes not selectable (or on second attempt)

### ISSUE THREAD

**Issue by MarvinKlar** [scribble-rs/scribble.rs#37] opened 2019-07-17 18:28 UTC
I haven't figured out, when this happens, ye(eeeee)t.

**Comment by Bios-Marcel** [comment] 2019-10-20 13:08
This is because some people can't properly click their mouse without moving it during clicking ^^

Could be avoided by just implementing the click on on mouseReleased instead of clicked I guess :man_shrugging:

**Comment by SZenglein** [comment] 2020-04-22 19:12
Looked into it a bit, and the problem is indeed this: 
> This is because some people can't properly click their mouse without moving it during clicking ^^

This is actually a significant usability issue, since with some hardware "just" clicking without dragging can be hard. Unfortunately the actual radiobutton which does handle this properly is hidden and only its styled label is shown, which behaves differently (at least on firefox, on chromium it works differently)

If we want to fix this properly for all browsers, we should probably use regular buttons. Looks like in any case regular button or radio behavior has to be emulated with Javascript.

**Comment by Bios-Marcel** [comment] 2021-01-15 12:16
This has been fixed.
Dupe of #162

**Closed by Bios-Marcel** 2021-01-15 12:16 UTC
Labels: bug
