### ISSUE TITLE
BUG: Docker building fails since update to go 1.16

### ISSUE THREAD

**Issue by tna76874** [scribble-rs/scribble.rs#215] opened 2021-02-20 18:28 UTC
Hi there,

I experience problems building the Docker-image with ubuntu 18.04 since commit b286294
Docker build log:
```
Sending build context to Docker daemon  4.567MB
Step 1/11 : FROM golang:latest AS builder
 ---> 05499cedca62
Step 2/11 : RUN mkdir /app
 ---> Using cache
 ---> 0e41d61277a3
Step 3/11 : ADD . /app/
 ---> b5d974d1bd94
Step 4/11 : WORKDIR /app
 ---> Running in 26dffe206b56
Removing intermediate container 26dffe206b56
 ---> 3b17358b3060
Step 5/11 : RUN make build
 ---> Running in 315a2f38fc5e
go: downloading golang.org/x/text v0.3.5
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/agnivade/levenshtein v1.1.0
go: downloading github.com/Bios-Marcel/discordemojimap/v2 v2.0.1
go: downloading github.com/dustinkirkland/golang-petname v0.0.0-20191129215211-8e5a1ed0cff0
go: downloading github.com/kennygrant/sanitize v1.2.4
go: downloading github.com/gofrs/uuid v4.0.0+incompatible
go: downloading golang.org/x/net v0.0.0-20210220033124-5f55cee0dc0d
communication/init.go:4:2: package embed is not in GOROOT (/usr/local/go/src/embed)
make: *** [Makefile:13: build] Error 1
The command '/bin/sh -c make build' returned a non-zero code: 2
```

Output of  `docker version`
```
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:13 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:25 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

If I build the image with the exact same docker version on ubuntu 20.04 the building process finish without errors. 

Any ideas how to resolve this?

Thanks and regards

**Comment by Bios-Marcel** [comment] 2021-02-20 18:31
>  Go version:        go1.13.15

out of date go

**Comment by Bios-Marcel** [comment] 2021-02-20 18:33
Closing, as it's not a bug, but an unsatisfied dependency.

**Closed by Bios-Marcel** 2021-02-20 18:33 UTC

**Comment by Bios-Marcel** [comment] 2021-02-20 18:45
not sure why golamg:latest pulls 1.13 doe, but i dont know anything about docker ^^

**Comment by tna76874** [comment] 2021-02-20 19:18
I'm also very confused here! On both systems (ubuntu 18.04 and ubuntu 20.04) the output of docker-version is the same. But on ubuntu 18.04 the building fails and on 20.04 not.

**Comment by Bios-Marcel** [comment] 2021-02-20 19:21
Hm, maybe it cached `golang:latest`? I thought it would always compare the hashes and redownload the tag if it's outdated.
As far as I know the `latest` tag by downfault is just a normal tag that's overriden again and again.
Maybe it's better to specify a certain go version there?

**Comment by tna76874** [comment] 2021-02-20 19:38
Indeed ! Thats it! I pulled again the image and it worked.
