### ISSUE TITLE
Ignore accented characters

### ISSUE THREAD

**Issue by zouglou** [scribble-rs/scribble.rs#115] opened 2020-04-20 01:34 UTC
Hello,

Just discovered Scribble, hacked it and had fun with it today!
I managed to ignore accented characters from proposed words (useful for languages like French, Skribbl.io does that too):

game/lobby.go - handleMessage():
```
lowerCasedInput := strings.ToLower(trimmed)
lowerCasedSearched := strings.ToLower(lobby.CurrentWord)
		
t := transform.Chain(norm.NFD, transform.RemoveFunc(func(r rune) bool {return unicode.Is(unicode.Mn, r)}), norm.NFC)
normInput, _, _ := transform.String(t, lowerCasedInput)
normSearched, _, _ := transform.String(t, lowerCasedSearched)

if normSearched == normInput {
...
```

Implies importing:
```
"unicode"
"golang.org/x/text/transform"
"golang.org/x/text/unicode/norm"
```

(I know I should have done a pull request but I'm not familiar with that for now, srry)

**Comment by Bios-Marcel** [comment] 2020-04-20 16:02
Hey,

thanks for the issue. I recommend you to check out the pull request stuff, it's really easy.

So, by accented characters you mean these `îêâ` kind of characters, right?

The function `transform.RemoveFunc` is deprecated, meaning that it could technically be removed or have bugs that won't be fixed or something like that. Instead you should use `runes.Remove`, which is also part of the standardlibrary, unlike the transform package. I am not sure whether that is applicable here. I haven't read into the Unicode normalization sets. If you have code such as this, it'd be really helpful to actually comment on it's single parts.Like, what exactly does the transform chain do in each step and why is the step necessary.

**Comment by hmenzagh** [comment] 2020-04-20 16:06
Yes as a french speaker I can confirm that removing accents like éèêàáï[...] is mandatory for the game to be playable and that Skribbl.io does it !

**Comment by zouglou** [comment] 2020-04-20 16:19
Yup, I will look for that!

Right, I had seen that for `transform.RemoveFunc`, but I spent a lot on a time on a first transform function that didn't work correctly (gave an empty string when there was a space), and I forgot to test it with `runes.Removes` afterwards :)

**Comment by Bios-Marcel** [comment] 2020-04-20 16:30
Honestly, I don't know what's correct and I don't really know how to test it. My knowledge of language isn't very huge and there's so many languages for which many weird cases exist I assume. For example, I am german and we have the letters `öäü`, however, simple replacing them with `oau` is wrong, since `öäü` actually stand for `oe ae ue`. I don't know whether french or other languages for that matter have similar cases.

The best thing for such code, would actually be to write a unit-test. I recommend that you look into that concept.  A unit-test basically exists only to verify that a small part of your code does exactly what you expect it to be. The good part about it is, that if you change the underlying code and accidentally break something, the unit-test will inform you right away and you can fix the breakage even before uploading it.

**Comment by hmenzagh** [comment] 2020-04-20 16:34
I don't have the time to help with unit-testing.
But I can **confirm** that in French you can remove all accents without issue the only catch it the letter `œ` that need to be replaced with `eo`

**Comment by zouglou** [comment] 2020-04-20 18:42
Can I bother you asking how do I make a pull request? I understand we create it on Github interface from another branch, but how do I push a branch?
I cloned the repo, made a branch, edited stuffs, committed, and then I should just push it back? If so, how to get permissions? Not so clear to me :( 

Should I push to a repo of mine first or something?

**Comment by kiwy42** [comment] 2020-04-22 09:19
here's the list of special characters in French at least: 
`À Â Æ Ç É È Ê Ë Î Ï Ô Œ Ù Û Ü Ÿ  
à â æ ç é è ê ë î ï ô œ ù û ü ÿ`
Looking at this I learn things and now know that there's Æ (alt gr+a) in 50 word in french.  
I'm French and had no idea that thing existed.  
I suggest if needed that only capital letters and accent should be ignore and special characters should be corrected in word list because as you mention, there might be infinite amount of special character in any language.

**Comment by zouglou** [comment] 2020-04-22 09:41
Yep, in #118 pull request, it's finally [github.com/kennygrant/sanitize/](https://github.com/kennygrant/sanitize/) that is used, and seems to cover both french and german cases (with an associative array) at least.

The problem with the first solution, though it covers all "non-spacing, marks", is, as I don't know every language where those characters are used, I can't be sure how this is supposed to be handle. 

(and about æ, don't you know that Gainsbourg song, "l, a, e dans l'a, t, i, t, i, a𝅘𝅥𝅮  "?)

**Closed** 2020-04-22 16:02 UTC
