### ISSUE TITLE
Feature request - New Game & Undo button

### ISSUE THREAD

**Issue by benl96** [scribble-rs/scribble.rs#152] opened 2021-01-07 08:13 UTC
Would be nice to have a New Game button when the Game ends so that you do not rely on having to execute the command in chat.

Unfortunately, there is currently also no possibility to undo his last step- in order to undo something you would currently have to delete everything with the trashbin.

**Comment by Bios-Marcel** [comment] 2021-01-07 15:24
Partially a duplicate of https://github.com/scribble-rs/scribble.rs/issues/138

I still don't think that this game should have an undo feature. Why do you think this is required? Isn't the eraser usually enough?

However, a new game (restart) button is needed for sure.

**Comment by Bios-Marcel** [comment] 2021-01-07 16:45
Oh btw, please don't mix different things into one issue.

**Closed** 2021-01-07 16:48 UTC

**Comment by Bios-Marcel** [comment] 2021-01-11 23:06
I've made the tool selection a bit more error prone. Instead of a full click, it now requires either a mouse press or mouse release. This probably prevents some accidental fills or erases :D

Also I am considering to add undo, but optionally, however, the lobby settings already kind of suck, I might wanna improve the homescreen before that.
